from . import account_move
from . import contact_master
from . import fleet_vehicle
from . import hr_expense
from . import location_location
from . import loyalty
from . import po_approval_master
from . import product_template
from . import purchase_order
from . import routes_details
from . import sale_order
from . import stock
from . import transport_details
from . import transport_entry
from . import setu_sales_incentive_structure
from . import setu_sales_incentive_structure_line
from . import gift_card_replication
from . import import_move_lines
from . import ho_store_configuration
from . import ir_cron
from . import ir_cron_history
from . import  last_scanned_serial_number
