# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'NHCL Customizations',
    'version': '1.0',
    'sequence': 1,
    'category': 'Purchase',
    "author": "New Horizons Cybersoft Ltd",
    "website": "https://www.nhclindia.com/",
    'summary': 'Purchase,Contact,Stock,Product Customizations',
    'description': """
This module contains all the common features of Transport and Check.
    """,
    'depends': ['purchase', 'base', 'stock', 'base_setup', 'product','hr','purchase_product_matrix','sale','purchase_stock','sale_stock','hr_expense','fleet','account','mrp','loyalty','stock_picking_batch'],
    'external_dependencies': {
                        'python': ['odf','openpyxl','xlrd','XlsxWriter'],
                    },
    'data': [
        'security/ir.model.access.csv',
        'security/sales_incentive_security.xml',
        'data/sequence.xml',
        'data/active_promo_cron.xml',
        'views/transport_menu.xml',
        'views/pos_dashboard_menu.xml',
        'views/transport_details_view.xml',
        'views/fleet_vehicle_view.xml',
        'views/routes_details_view.xml',
        'views/location_view.xml',
        'views/transport_entry_view.xml',
        # 'report/dev_transport_report_template.xml',
        # 'report/dev_transport_report_menu.xml',
        # 'report/delivery_slip.xml',
        'views/contact_master.xml',
        "views/purchase_approval_buttons.xml",
        "views/sale_order_view.xml",
        "views/account_move.xml",
        'views/product_template_views.xml',
        'views/stock_views.xml',
        'views/loyalty_program_view.xml',
        'views/stock_batch_views.xml',
        'views/loyalty_view.xml',
        'views/hr_employee_view.xml',
        'views/res_config_settings_view.xml',
        'views/import_move_lines_view.xml',
        'views/setu_sales_incentive_structure_views.xml',
        'views/setu_sales_incentive_structure_line_views.xml',
        'views/cv_ir_cron_history.xml',
        'views/ir_cron_views.xml',
        'views/ho_store_configuration_view.xml',
        'report/setu_sales_person_incentive_detailed_report.xml',
        'report/setu_sales_person_incentive_summary_report.xml',
        'report/barcode_sheet_delivery.xml',
        'report/credit_note_pos.xml',
        'report/transfer_note.xml',
        'report/new_otd_report.xml',
        'report/account_transfer_out.xml',
        'wizard/pos_exchange_popup.xml',
        'wizard/import_order_lines_view.xml',
        'views/last_scanned_serial_number.xml',
        'wizard/purchase_pt_upload_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'nhcl_customizations/static/src/js/multiselect.js',
            'nhcl_customizations/static/src/js/pos_dashboard.js',
            'nhcl_customizations/static/src/js/patch_list_width_render.js',
            'nhcl_customizations/static/src/xml/pos_dashboard.xml',
            'nhcl_customizations/static/src/css/style.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
